#!/usr/bin/env python
##HACKABOT_HELP##
# Looks up wow items on wowhead. 
# [item name]
##HACKABOT_HELP##

import urllib
import re
import sys
import amara
import hackabot
from hackabot.client import Client


hbc = Client()
msg = hbc.readline()
nick = hbc.sent_by()

if re.search(r'how do they work?', msg, re.IGNORECASE):
  print "send %s: How about you ask Shaggy 2 Dope?" % (nick)
